##I got to start over again :(##
##"Help the others prepare dinner."##
"I have nothing else to do, so I head over to the kitchen where Kumano and Mikuma are preparing dinner."
"I guess they need help, since Suzuya is already preoccupied with reading some gossip magazine."
i "You guys need help?"
ku "Oh! It would be lovely if you gave us a helping hand."
"Kumano and Mikuma scoot down to make some space for me."
ku "If you want you can get started on preparing the vegetables with Mikuma while I start preparing the curry."
i "Yes ma'am."
mk "There's really no need to be so well-behaved, Ibuki!"
i "R-really?"
mk "We're not commanding officers or anything!"
i "oh...sorry."
"It's really hard to really grasp how to act around people your own age when your whole life was just sitting around a military base."
"Hell, these girls have different uniforms compared to the military uniform I have."
"It's just seems so strange, almost unreal, that these girls fight out there wearing a school uniform."
mk "...Ibuki? You okay?"
i "Ah, yeah."
mk "That's great! Here, can you help me out a little bit with the potatoes?"
i "Yes ma'am -- ah--"
"Mikuma stares at me and pouts."
i "Ahaha... sure thing."
##time pass##
##PLEASE HELP ME ON MULTIPLE CHARACTERS##
girls "Itakadimasu!"
mg "Woah! Kumarinko, the curry's is much better than last time!"
mk "Yeah, I know right? It's probably because Ibuki helped us out this time."
i "Y-you guys don't need to praise me...I didn't even do much work either -- Kumano did most of it, you know, making the curry sauce."
ku "There's no need to downplay your part. Your job was just as important to myself and Mikuma."
i "ah...okay."
"I just go back to eating my curry and rice."
sz "Not the very talkative type, eh?"
mk "Give her some time, I mean, she's a transfer from another base."
mg "And it wasn't like you were super friendly when you first got here!"
"Mogami gives off a teasing smile."
sz "Whatevs, Mogamin."
"The girls continue to banter with another while eating dinner."
"All while I sit at the edge of the table, so lost in thought I could barely distinguish the words they were saying."
mg "...buki?"
"This just feels so alien and unsettling. I was never used to talking to people or having conversations with anyone."
"I just did my job."
"Was that not good enough?"
mg "yo, Ibuki~"
i "...huh?"
mg "Since Suzuya's feeling pretty lazy, do you want to take out the non-burnables?"
