label baseline_1:
scene dorm hallway
"I keep moving forward. It's her problem, not mine."
"After a bit more time, I finally arrive to my dorm."
scene dorm door
"16, he said."
"Well... this is it."
"I gently open the door."

scene crudiv7room
show suzuya
with easeinbottom
show kumano
with easeinbottom

"There are two girls, both sitting at a table, frozen mid-conversation to look at me."
"The room fills with an unsettling silence as I just stand there, A million questions of self doubt and harassment racking my brain as the girls seem to stare straight at me."
"Part of me really wants to just close the door and leave, but my body is paralyzed in utter horror as I try and sputter out some phrase to cut the silence."
i "Ah.."
"Before I can continue making a complete and utter fool of myself, one's already jumped up and right next to me."
bhg "Ooh, ooh, new girl! I haven't seen you around here."
"The other girl gently smiles as I excuse myself and close the door behind me. She seems much more... calm."
i "I-I'm Ibuki. I was just posted here. I was told I'd be with cruiser division 7?"
bhg "You're in the right place then! I'm Suzuya!"
"She steps back for a moment and extends her hand for a shake. I accept, almost awkwardly."
"It feels almost uncomfortable. I'm not used to these gestures."
"The brown haired girl gets up from the table and walks up to greet me."
brg "And I'm Kumano. Welcome to the Wagyu Naval Base."
i "I...Thank you both."

ku "So, how are you liking the base so far?"
i "It's... alright. I'm sure everyone here is nice, though."
sz "Sounds good! I bet you'll find this place lovely!"
"I look around the room. There's four other doors, all with their own names. I wonder who they belong to?"
i "Are there more people in this cruiser division?"
sz "Yep! Mogami and Mikuma are out right now."
ku "They should be training with their squadron at the moment. I think they'll be back soon."
i "I see."

ku "Have you met any of our admirals yet?"
"..Wait...there's more than just Scoots?"
i "I've only met [scPrefix] Scoots, though that one woman I ran into earlier didn't seem like a shipgirl."
i "Oh, and I've heard what who I've been told is Daisho." 
##Wow, I'm offended.##
ku "There are plenty more, maybe you'll find one you like. Who have you been assigned to?"
i "I actually haven't been assigned to any unit yet. The [scPrefix] said that the system wasn't working."
sz "That's weird... You can hang with us for the time being if need be."
ku "Ufu, Akashi and Yuubari are going to have a field day. Not that they have much to do in terms of combat." 
i "..Akashi? Yuubari?"
ku "they're ladies who specialize in technology and repairs. You will meet them soon enough after you get used to sortieing."
##Tea scene##
ku "That reminds me, while we're waiting for the other two girls to return, would you like to join us for tea?"
"Tea? Isn't that for old people and ceremonies?"
"In spite of living in Japan my whole life, most of it was pretty sheltered inside the naval base."
"I never really got to know much about the culture outside of holidays and special broadcasts on television."
"Suzuya reads the confusion on my face, and abruptly turns to Kumano."
sz "Jeez, Kumano! She's looking at us like we're old geezers!"
"...geezers?"
i "Ah, I didn't mean to come off that way! I just don't know how to do this whole tea thing...is it some sort of ceremony?"
"The room is awkwardly silent for a moment, until Kumano lets out a light laugh, coming in short staccato arpeggios, almost sounding like a dolphin, before re-composing herself."
ku "Of course not! It's more of a casual tea time that me and the other ladies of the Seventh Cruiser Division have from time to time."
sz "Most of the time it's just me and Kumarinko though."
i "And what do you do for this 'tea time'?"
sz "Ah, we mainly talk about gossip and cute dudes around the base. Like this one dude that I talked about the other day? {i}Total hunk.{/i}" 
##Suzuya is presumably referring to Flat##
sz "I mean, sure, most of the time he wears that dingy uniform, but when I saw some of Aoba's photos of the staff changing room circling around the other day, I managed to snag a picture of him!"
sz "ugh, sometimes it makes me wish that the staff wore some swim trunks or something more revealing...there's only so much my male model calendar can d--"
"Suzuya's ramble about hot guys is suddenly cut off when she notices Kumano's slightly annoyed glare."
"Suzuya coughs."
sz "...And snacks. We've got snacks."
"Suzuya gestures to the assortment of cookies and convenience store snacks lying around the table."
"Well, that was one long, somewhat complicated explaination."
"Though I guess it would be nice to chat with girls my age, since all I ever interacted with were mostly guys from the JMSDF, doctors and clinicians."
"Even though I barely know how girls act...It's worth a try."
i "Well, I'll gladly accept your invitation."
"Kumano waves me over to the table, offering a seat at another cushion."
"Suzuya quickly returns to her seat. I lay my backpack next to the table and join them while Kumano pours green tea from the kettle and gives it to me."
i "Oh, Thanks."
ku "No problem, dear."
"I carefully take a sip from the mug. The tea is warm with a creamy smooth texture and a bitter taste, but manages to fill my body with warmth."
"Kumano looks at me."
ku "So, tell us a little about yourself."
"Myself? Like my past?"
i "Ah, well, from what I know, I was first laid down in april 24, 1942 as the successor to the Mogami-class cruisers, until I was ordered to be converted to a Light Aircraft Carrier in 1943 after the disaster at Midway."
"However, my construction was delayed to make way for submarines up until after the war in 1946--"
sz "Gaah! That's the stuff I can read at the naval library. Geez, what Kumano meant was {i}yourself{/i}. Like your childhood or something."
i "Childhood?"
ku "Allow me to explain. When someone asks about your upbringing, they are referring to the experiences you had in your early life."
i "Oh, so that's what it means?"
ku "Yes, in a sense."
"As I explain my life stationed at my previous base, Kumano takes a sip of her tea. There's something almost cordial and proper about the way she holds the cup in her hands."
"She delicately lifts the cup, closing her eyes to take in the bitter taste of the matcha before gently setting the cup back on the table."
"Suzuya, on the other hand, tends to drink from the teacup in a very casual manner, almost haphazardly. Her arm reaches over to the plate of cookies as the other holds the mug to her lips."
"Even if they are sister ships, they both seem very different. They don't even look or act remotely similar to each other, yet somehow, they get along."
"Is this what friends are like?"
##is it good?##
"I'm deep in thought, observing the interactions between the two girls when the door starts fidgeting, like someone is unlocking it." 
"The door flies open, revealing two other girls. Both are wearing matching uniforms."
shg "HEEEEeeey!..?"
shg "Oh, who's this?"#owo
"I get up and bow, introducing myself."
i "I'm Ibuki, I was just stationed here."
shg "Well then, I'm Mogami. And this here is Mikuma."
"Mikuma pops out from her side and says a little 'hi'. The two move over to the table and sit down."
mk "Wait, you just arrived here? Shouldn't you be with your ship class?"
mg "Yeah, I don't remember an Ibuki within the Mogami class..."
i "I'm actually the only one in my class... I was told by [scPrefix] Scoots that I'd be with CruDiv 7 for the time being."

mg "I don't think we have any more rooms in here... But you can have mine! I'll just bunk with Kumarinko from now on."
mk "Waitwaitwaitwai-"
mg "There's not much stuff in my room so it should be fine!"
"I doubt Mikuma is consenting to this."
mk "We don't even have actual bunks! How are we supposed to do that?"
mg "I can always pull up a sleeping bag. Or, you know~"
sz "We can always just ask Yuubari, Akashi, or Ooyodo for a bunkbed in your room."
mk "But-but.."
mg "We gotta be nice to the newface, alright?"
mk "Fiiiine."
mg "There we go! I'll get my stuff moved over really quickly."
"She quickly runs off into her room. There's a lot of crashing noises and other various worrying sounds coming from it."
i "Is she okay in there?"
mk "Mogamin's a bit clumsy, but I think she's fine."
"Moments later Mogami exits her room, albeit with a bunch of scratches. She still stands strong, backpack in tow."
mg "Alright, I'm good now! Ibuki, you're good to move in now. Now, if you excuse me-"
"She quickly runs into Mikuma's room, only for Mikuma to chase right behind her."
i "I guess I'll take my leave now."

"I get up to check out the room, but as I do, some yelling reverberates through the door."
i "Who was that?"
ku "Must be some other cruisers. Certain classes don't mix well with others."
menu:
    "Should I check the commotion or go back to setting up my room?"
    "Check out the argument.":
        $ aobaInvest = True
        jump aobaka_route_1
    "Go back to unpacking.":
        i "Ah, I see."
"Who would've thought that this base still has its arguments?"
"Doesn't seem too bad from what I've seen."
"Suzuya and Kumano go back to their previous conversation as I head over to my new room."
scene dorm room empty
"Welp, time to get to business."
return
i "..I think that'll do"
"I dust my hands off and take a moment to look at my room. There isn't much I brought with me, just a few bedsheets and a calendar that hasn't been updated in weeks."
"It's pretty simple, but after getting a small tour of each of the Seventh Cruiser Division's rooms, I feel kind of bad that I brought so little."
"Not that I had much to bring anyway, besides, I'm nothing but a blank slate."
##not so obvious jab on how Ibuki the MC, therefore has no personality##
##later on in the story, I plan on Ibuki developing a personality. I think that will be her character development.##
"My thoughts were cut off short when the door creaks open, and Mikuma peeks in."
mk "Hey Ibuki, the other girls and I made dinner. Be sure to head into the common room to eat with us, Okay?"
##scene change: common room (evening)##
"The room is filled with lively chatter of teenage girls and the aroma cooked meat, curry and miso soup."
"And admist in it all, I sit in my chair at the end of the table, ignoring the conversation and poking at the Wagyu beef with my chopsticks."
"The girls know each other so well, yet I feel so out of place, like if I don't belong here."
##add more stuff here##
ku "Ibuki dear, how was the food?"
i "Ah, was really good. I'm suprised."
sz "That's right! It's because Mikuma and Mogami made it!"
"Mogami gives a mervous smile while scratching the back of her head."
mg "d'awww, you don't have to say that, Suzuya! You're embarassing poor me and Mikuma over here!"
ku "Flattery aside, you ladies make wonderful food. Now then, shall we finish this off with some Rosehip tea?"
mg "Sure, I just need to clear my plate. One sec."
"Mogami walks over to the kitchen to dispose of the compost when she opens the trashcan she furrows her brow."
mg "Ah, it already looks full..."
"I get gut this feeling to help, since I feel kind of bad not really providing much into the conversations during dinner..."
menu:
    "What should I do?"
    "Take out the trash by myself"
    ##jumps to Alpaca's route##
    "Help Mogami take out the trash"
    ##common route##
i "Hey Mogami, if you want I can help you out with that."
mg "Really? Aw geez, thanks man! How about you get one side and I'll get the other, 'kay?"
i "Yeah..."
"I awkwardly shuffle around the trashcan and grab two small corners, trying not to dirty my hands the smell of rotting compost."
mg "on the count of three! one...two..."
"it takes quite a bit of shuffling around until the trash bag slides out of the can."
mg "...three! Kay dudes, take care and don't burn the dorm down while me and Ibuki take out the trash!"
"Kumano lets out another dolphin-like giggle."
ku "We'll try not to." 
scene [Trashmen]
 "In just a couple minutes from our arrival at the dumpster, Mogami effortlessly swings the last of the garbage bags into the dumpster, landing with a hearty thud. She dusts her hands and then sighs."
mg "...And I think that's it."
i "I'm impressed. You didn't even need my help."
mg "Yeah, it's because I have been working out, ya'know? These boys can't pack a punch without some hard work..I guess."
"Mogami lets a sheepish chuckle, when a voice cuts short the awkward flexing."
mv "...if only working out could save you from your clumsiness, though"
##sad mogamin noises##
mg "uweeeh..."
"I turn around in the direction of the voice to see this strange looking girl with light melon colored green hair tied up in a ponytail."
"She's casually leaning up against the wall looking at us in slight amusement, as if she was observing us."
ghg "didn't know you brought in a newbie, Mogamin."
"The girl gets up and walks over to me with a slight bounce in her step and extends her hand out to me and smiles."
ghg "the name's Yuubari, nice to meet ya!"
"I get a little anxious at first, seeing this cheerful girl having no qualms about being out here at night..."
"But in spite of my worries I accept her friendly gesture and shake hands."
i "mhm, same to you."
mg "This here is Ibuki."
"Mogami playfully puts an arm around my shoulder."
mg "She recently transferred here today, so please be easy on her when she's doing training exercises and getting used to rigging."
"...rigging?"
i "excuse me wha--"
yuu "Mkkay, sure can do! I'll see you tommorow, Ibuki!"
"..and just like that, she disappears."
"mogami looks to where she ran off into the night with a small smile on her face."
mg: "What a strange girl, that light cruiser. Well," 
"she turns back towards me."
mg: "let's get back to the dorm."
##scene change: Ibuki's room##
"I open my door into the silent darkness of my unfamiliar room. My shadow falls on the carpet, framed by the incandecent light behind me."
"I can't say this wasn't anormal. My room back at my previous base wasn't any better."
"But being around girls my age made me feel like there is something I lack."
"Deep down there's this feeling that I know I don't fit in."
"I'm just a forgien observer, almost wedged in there by force."
"But in spite of knowing this truth, there's a part of me that doesn't want to accept it."
"I make my way to my bed and fall into the bedsheets, trying to take my mind off of my fears. Trying to focus on the day ahead as a drift off to sleep."
"Training excercises, huh...."
##scene 1 finished##
