label wororg_1:
$ woggyYes = True
i "Don't worry about it. I'm actually new around here, just arrived here this morning. I'm Ibuki."
wg "Good to meet you, Ibuki. My name ist Christian, but ze others around here just call me Wororg, {i}quack{/i}."
wg "Task group leader of 1-1 und vize kommander of ze Deutsch mission to ze Joint Anti-Abyssal Staff."
"He extends his hand, offering a handshake, and I accept. Your training has done me well, Suzuya."
"The admiral waves me over to some railing and leans on it, looking out to the sea."
wg "So, who are you currently stationed vith?"
i "I'm currently with Cruiser Division 7, though I haven't been assigned to anyone yet."
wg "I think you'll like it here. The people are nice, and I'm sure you vill find it interesting, ja?"
i "Yeah... already met a bit of the weird bunch I bet."
"His voice resounds throughout the pier. Both soft and stern, probably due to his accent."
wg "Ve're currently short in ein-zwei, but I think I can get you vith us in our squadron."
wg "Think Saxon'll let you in? Ooyodo might have her say, though. {i}quack{/i}"
"He slowly conceals his hand in his coat before digging around and unveiling a... coffee cup?"
"Somehow, the cup seems to be hot despite being a simple paper cup... how long would it be in there anyways?"
"The admiral takes a quick sip from the cup before looking back at me."
wg "Vant some? Good Deutsch brew."
i "No, thank you. Who's Saxon and Ooyodo? I've heard their names be tossed around here and there, but I haven't met them yet." #bit mixed on the second & third sentences
wg "Herr Saxon ist ze second-in-kommand in the Staff, und ze kommander of ze Deutsch mission."
wg "Und Frau Ooyodo ist ze kommanding secretary here. She makes ze plans und announcements."
i "I see. I'll probably be meeting Ooyodo soon. Saxon must be your boss, then?"
wg "Of sorts. He ist kind of mysterious. Appears when he ist needed, and nothing more. Also for D&D."
i "Hmm. Hope he'll let me in, then."
"Wororg nods before taking another sip. Looking off into sea, I wonder how the others will be."
"Suddenly, buzzing from Wororg's phone disrupts the silence. He pauses before pulling it out."
wg "Ah, scheisse. Almost forgot about another meeting."
wg "Well, I vill be seeing you around, Ibuki. Have a nice stay."
"He nods to say goodbye and quickly scurries away to his duties. I guess I'll keep exploring the harbor."
"Moving down the pier, I go back to exploring this part of the base. It feels smaller yet more spacious than my old JSDF homes."
jump harbor_1_5
return
